networks:
  default:
    name: geor



services:
  redis:
    image: "redis:alpine"
    command: redis-server

    environment:
      - REDIS_REPLICATION_MODE=master
  gaia-back:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile_flask
    volumes:
      - ../../datadir:/etc/georchestra
      - ../gunicorn.conf.py.example:/geordash/gunicorn.conf.py:ro
      - ../config.py.example:/geordash/config.py:ro
      - ../geordash/celeryconfig.py.example:/geordash/geordash/celeryconfig.py:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      #- ../:/geordash
      # need to add path of geonetwork and geoserver datadir in here

    ports:
      - "5002:5002"

    environment:
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      CURL_CA_BUNDLE: ""
      FLASK_APP: geordash
      FLASK_OPTS: "-h 0.0.0.0 -p 5002"
      georchestradatadir: /etc/georchestra
      REDISURL: "redis://redis:6379/1"
      PGHOST: database
      PGPORT: 5432
      PGDATABASE: georchestra
      PGUSER: georchestra
      PGPASSWORD: georchestra
      ANALYTICS_HOST: analytics
      CAS_HOST: cas
      CONSOLE_HOST: console
      GEONETWORK_HOST: geonetwork
      GEOSERVER_HOST: geoserver
      HEADER_HOST: header
      GEOWEBCACHE_HOST: geowebcache
      MAPSTORE_HOST: mapstore
      DATAFEEDER_HOST: datafeeder
      IMPORT_HOST: import
      DATAHUB_HOST: datahub
      OGC_API_RECORDS_HOST: ogc-api-records
      KB_HOST: kibana
      KB_PORT: 5601
      ES_HOST: elasticsearch
      ES_PORT: 9200
      RABBITMQ_HOST: rabbitmq
      # needed for geonetwork entrypoint DO NOT REMOVE
      CONSOLE_URL: http://${CONSOLE_HOST}:8080
      # needed for kibana DO NOT REMOVE
      ELASTICSEARCH_HOSTS: http://${ES_HOST}:${ES_PORT}
      FQDN: georchestra-127-0-0-1.nip.io
      GEOSERVER_DATA_DIR: /mnt/geoserver_datadir


  gaia-celery:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile_celery
    volumes:
      - ../../datadir:/etc/georchestra
      - ../gunicorn.conf.py.example:/geordash/gunicorn.conf.py:ro
      - ../config.py.example:/geordash/config.py:ro
      - ../geordash/celeryconfig.py.example:/geordash/geordash/celeryconfig.py:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      #- ../:/geordash
      # need to add path of geonetwork and geoserver datadir in here

    environment:
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      CURL_CA_BUNDLE: ""
      FLASK_APP: geordash
      FLASK_OPTS: "-h 0.0.0.0 -p 5002"
      georchestradatadir: /etc/georchestra
      REDISURL: "redis://redis:6379/1"
      PGHOST: database
      PGPORT: 5432
      PGDATABASE: georchestra
      PGUSER: georchestra
      PGPASSWORD: georchestra
      ANALYTICS_HOST: analytics
      CAS_HOST: cas
      CONSOLE_HOST: console
      GEONETWORK_HOST: geonetwork
      GEOSERVER_HOST: geoserver
      HEADER_HOST: header
      GEOWEBCACHE_HOST: geowebcache
      MAPSTORE_HOST: mapstore
      DATAFEEDER_HOST: datafeeder
      IMPORT_HOST: import
      DATAHUB_HOST: datahub
      OGC_API_RECORDS_HOST: ogc-api-records
      KB_HOST: kibana
      KB_PORT: 5601
      ES_HOST: elasticsearch
      ES_PORT: 9200
      RABBITMQ_HOST: rabbitmq
      # needed for geonetwork entrypoint DO NOT REMOVE
      CONSOLE_URL: http://${CONSOLE_HOST}:8080
      # needed for kibana DO NOT REMOVE
      ELASTICSEARCH_HOSTS: http://${ES_HOST}:${ES_PORT}
      FQDN: georchestra-127-0-0-1.nip.io
      GEOSERVER_DATA_DIR: /mnt/geoserver_datadir
